name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew
        working-directory: homeletter-twa

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace
        working-directory: homeletter-twa

      - name: Archive APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: homeletter-twa/app/build/outputs/apk/debug/*.apk